### ISSUE TITLE
添加离线版本？

### ISSUE THREAD

**Issue by huangzworks** [acl-translation/acl-chinese#15]
刚才有读者来信咨询下载版的事情。

ReadTheDocs 实际上提供了下载离线版本的功能，不过比较难找，要不要在主页加一个链接，将链接放上去呢？

https://media.readthedocs.org/htmlzip/ansi-common-lisp/latest/ansi-common-lisp.zip

**Comment by tangxinfa** [comment]
readthedocs 上下载的是繁体中文版的，简体中文版怎么下载呢？

**Comment by tangxinfa** [comment]
明白了，epub 同时包含繁体版和简体版，简体版在后面
